class TambahData {
  btnTambah = ":nth-child(3) > .menu-link"
  tambah = ".btn-group > .font-weight-bolder"
  nokk = "#pemilih_kk"
  nonik = "#pemilih_nik"
  nama ="#pemilih_nama"
  alamat ="#pemilih_alamat"
  rt = "#pemilih_rt"
  rw = "#pemilih_rw"
  tanggal_lahir = "#pemilih_tgl_lahir"
  tempat_lahir = "#pemilih_tempat_lahir"
  jk_laki = ".col-8 > .radio-inline > :nth-child(1)"
  status_pemilih = "#Statusradio > :nth-child(2) > span"
  kelurahan = "#select2-pemilih_kelurahan_id-container"
  dropdown = ".select2-results__option"
  status_kawin = "#select2-pemilih_status_kawin-container > .select2-selection__placeholder"
  caleg ="#select2-pemilih_caleg_id-container"
  tps = "#select2-pemilih_tps_id-container"
  btn_save = "#btn-simpan"

  msgKK = ":nth-child(1) > :nth-child(1) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgNIK = ":nth-child(1) > :nth-child(2) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgNama = ":nth-child(3) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgAlamat = ":nth-child(1) > :nth-child(4) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgRT = ":nth-child(1) > :nth-child(5) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgRW = ":nth-child(1) > :nth-child(6) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgKelurahan = ":nth-child(7) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgTmptLhr = ":nth-child(2) > :nth-child(1) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgTtgLhr =":nth-child(2) > :nth-child(2) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgJK =".col-8 > .fv-plugins-message-container > .fv-help-block"
  msgSKwn = ":nth-child(2) > :nth-child(4) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgCaleg =":nth-child(2) > :nth-child(5) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgTps = ":nth-child(2) > :nth-child(6) > .col-lg-8 > .fv-plugins-message-container > .fv-help-block"
  msgStatus = "#errorStatus"
  errorKK = "#error_kk"
  errorNIK = "#error_nik"

  editBtn = ":nth-child(1) > :nth-child(8) > .btn-icon-warning"
}

export default TambahData;
